### ISSUE TITLE
deprecation of 1992 terms

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#12]
vocabs that have either been deprecated from the 2011 version that were in the 1992 version

They are either deprecated and not replaced, which is currently noted in skos:note. Example  - 
dcterms:identifier "http://anzsoil.org/def/au/scma/1
skos:note "Retired in Soil Chemical Methods Australasia, Rayment G.E. and Lyons D.J. ISBN 9780643101364

or replaced. Example 
dcterms:identifier "http://anzsoil.org/def/au/scma/14E2
dcterms:isReplacedBy <http://anzsoil.org/def/au/scma/14E2a> 
dcterms:isReplacedByhttp://anzsoil.org/def/au/scma/14E2b
skos:note "14E2 has been superseded by 14E2a and 14E2b in Soil Chemical Methods Australasia

In both cases, should these also be deprecated? 

possibly using - 
owl:deprecated a owl:AnnotationProperty ;
     rdfs:label "deprecated" ;
     rdfs:comment "The annotation property that indicates that a given entity has been deprecated." ;
     rdfs:domain rdfs:Resource ;
     rdfs:isDefinedBy <http://www.w3.org/2002/07/owl#> ;
     rdfs:range rdfs:Resource .

**Comment by abigg92** [comment]
not sure the context that 'deprecated' is being used here, but in theory, once a method code is created it remains valid forever as it was the code in use at that point in time.  This gets into the difficult space of code migration - do you or don't you.  For example, when we built SALI in Qld, we decided to migrate all red book (=YB1) codes to YB (YB2) to make things consistent.  We were also migrating from older code formats.  Do you migrate codes every time new codes are created (and assume everything is the latest version) or do you have your codes defined in terms of the edition of the reference they come from?  Wait until you get into colour books - whole world of pain there

**Comment by meganrwong** [comment]
It seems what we need is a label 'superseded' where there is a new version green book term replacing it dcterms:isReplacedBy 
And, if there is no new procedure replacing it, we just leave as is (ie don't call it 'deprecated')
Just need to find an identifier/vocab for 'superseded'.....
