### ISSUE TITLE
Managing and rendering method descriptions

### ISSUE THREAD

**Issue by dr-shorthair** [ANZSoilData/def-au-scma#13]
I have split up ch9 into separate files, one for each procedure - see https://github.com/ANZSoilData/def-au-scma/tree/main/html/9-P
No editing, just a copy of the relevant lines of HTML from the chapter.

These fragments could be used  
(i) as the **_value_** for the skos:definition which requires each to be copied over into the TTL file
(ii) stored separately and accessed as a **_link_** from `skos:definition`. 

You can get each of these to render OK using raw-githack. 
For example this source https://raw.githubusercontent.com/ANZSoilData/def-au-scma/main/html/9-P/9D1.html 
renders as https://raw.githack.com/ANZSoilData/def-au-scma/master/html/9-P/9D1.html 
I am not (yet) suggesting a definite implementation pattern, just exploring the burden of some options.
These examples could be evaluated to see if there is a (semi-)consistent layout and headings.

Would this be acceptable as at least an initial implementation pattern @peterwilson @ljgregory

**Comment by meganrwong** [comment]
Thanks @dr-shorthair  

Here is my first go. Chapter 2. It appears to have worked

this source: https://raw.githubusercontent.com/anzsoildata/def-au-scma/main/html/2/2A1.html
renders at: https://raw.githack.com/anzsoildata/def-au-scma/main/html/2/2A1.html

I've had a look through how chpt 2 and 3 renders and noted some small issues here we may (or may not) want to resolve in each fragment going forward w other chapters

**Comment by meganrwong** [comment]
from here: https://github.com/ANZSoilData/def-au-scma/tree/main/html/2

I will continue with the other chapters in this way.

**Comment by meganrwong** [comment]
line 7  https://github.com/ANZSoilData/def-au-scma/blob/main/html/3/3.html

soil rending as soÕl  , code - so&#213
relationships as relatŠnships, code - &#352

Appears this way in ePubs version 
May be issue w table header text as soil and relationships appear fine elsewhere 

see - https://raw.githack.com/anzsoildata/def-au-scma/main/html/3/3.html#ch3tab1

**Comment by meganrwong** [comment]
line 4 at https://github.com/ANZSoilData/def-au-scma/blob/main/html/3/3A1.html
'details' rendering as 'detaÕs'. Code  deta&#213;s
<p class="caption1"><a id="page_21"></a><a id="ch3tab2"></a><strong>Table 3.2.</strong> Summary deta&#213;s of laboratory and field methods described in this chapter.</p>
see https://raw.githack.com/anzsoildata/def-au-scma/main/html/3/3A1.html

See again, in 3D1 "Table 3.3. Examples of approximate Eh values for soÕs of different oxidatŠn status and at points of transitŠn for important redox pairs at pH 7.0." 

it is text for table header  - so appears to be recurring through table header texts of each html fragment

**Comment by meganrwong** [comment]
Are we happy w tables?
eg see
https://raw.githack.com/anzsoildata/def-au-scma/main/html/3/3D1.html
We loose lines and shading

**Comment by meganrwong** [comment]
in https://github.com/ANZSoilData/def-au-scma/blob/main/html/2/2.html
line 66
we loose shading of boxnote, and a text issue 'b&#352;security'
<p class="para"><strong>IMPORTANT:</strong> Laboratory managers and staff should ensure, for **b&#352;security** reasons, that their sample acceptance and sample disposal procedures are lawful.</p>
</div>

see 
https://raw.githack.com/anzsoildata/def-au-scma/main/html/2/2.html

**Comment by meganrwong** [comment]
References - links to relevant refs fragment required

**Comment by dr-shorthair** [comment]
I am reluctant to get involved in copyediting at all - that would be a never-ending task, with a risk of shading over into content-editing which is definitely out-of-scope. And the ePub has most of these character-set errors anyway. 
 
The one thing we might do is to grab the CSS so that the styling is better. (might fix the shading in tables)

**Comment by meganrwong** [comment]
we - with @amacleod-cerdi added stylesheet to 
https://github.com/ANZSoilData/def-au-scma/tree/main/html/styles

html/head/body tags, CSS reference and Doctype added 
see example 
https://raw.githack.com/ANZSoilData/def-au-scma/main/html/2/2.html

Seems to have improved styling

**Comment by dr-shorthair** [comment]
That's good to see. 
To carry this through, the `head` and `body` would need to be added to all the fragments. 
(I did realise that we were winging it before by not including them)

BTW - in https://github.com/ANZSoilData/def-au-scma/blob/main/html/2/2.html line 2, I think `<html` should be `<head`. 

And then you should add closing `</body>` and `</html>` tags at the end. 

all done

**Comment by meganrwong** [comment]
yep, has </body>
</html> tags at end

**Comment by meganrwong** [comment]
you will see I've also done at https://github.com/ANZSoilData/def-au-scma/commits/main/html/2/2.html
&#213;  - Õ . Replace with il, as in detaÕs and soÕs
&#352; – Š . Replace with io, as in oxidatŠn, transitŠn, relatŠnships, bŠsecurity 
This seems like two recurring issues throughout that a find and replace will fix. I agree copyediting could be a slippery slope, and is out of scope, so I will stop looking for more problems  ;)

**Comment by dr-shorthair** [comment]
I fixed a couple more nits. I think you now have a pattern that can be used to wrap all the HTML fragments.

**Comment by meganrwong** [comment]
Excellent. Will find chunks of time to work through rest of chapters asap

**Comment by meganrwong** [comment]
I notice we don't have chapter numbers at top of. for example https://github.com/ANZSoilData/def-au-scma/blob/main/html/9-P/9.html  ie didn't include "chapter09" 

Small thing, but was this an intentional decision @dr-shorthair ?

**Comment by dr-shorthair** [comment]
"Chapter 9" isn't in the header in the XHTML source https://github.com/ANZSoilData/def-au-scma/blob/main/source/xhtml/chapter09.html

So it would require manually inserting. Maybe a good idea to remind readers where it is the Green Book. But I think part of the goal is to get away from a sequential chapter-based list, and rather to go to a continuously updated register with non-sequential identifiers?

**Comment by ljgregory** [comment]
The chapters are focused on particular properties. Perhaps you would still want to group them in this way, even after obtaining the ideal world registers that are governed in a systematic way?

**Comment by dr-shorthair** [comment]
> Perhaps you would still want to group them in this way

I understand that grouping them by property is useful. But "Chapter 9" is less informative than "Phosphorus" - i.e. grouping on a recognisably-labelled facet.

**Comment by ljgregory** [comment]
I agree, but the grouping doesn’t change, just the name of the group right?

**Comment by dr-shorthair** [comment]
A short term goal would be to add some indexing information to every entry in a structured way. e.g. 
```
    sosa:observedProperty P01:MPPSP012 .
```

or
```
    schema:variableMeasured CAS:7723-14-0 .
```

That way you could show 'all the methods for measuring phosphorus' without needing to know 'Chapter 9'. 

(See https://vocab.nerc.ac.uk/collection/P01/current/MPPSP012/ )

**Comment by meganrwong** [comment]
hmmmm. I take your point Simon re moving away from a sequential chapter based list. Yes, they are grouped together anyway. And yes, I think that in future versions linking to all the Obervable Properties the methods can measure. Certainly needs soil chemists endorsing these relationships as it is not a straight forward job - see https://github.com/ANZSoilData/def-au-scma/issues/8

But, I have found that people refer to 'chapeter 3' etc - just becuase of being familiar with the book for years

btw - seems chapter number was in a header for pH  - I put it here as test - 
 https://github.com/ANZSoilData/def-au-scma/blob/main/html/4-pH/test%20chapter%20header.html

**Comment by meganrwong** [comment]
by the way I did pH today, just working thorugh getting an efficient 'batching' process happening for getting each chapter up
https://github.com/ANZSoilData/def-au-scma/tree/main/html/4-pH

**Comment by meganrwong** [comment]
I will leave the chapter numbers out as a header. They don't make much sense to use in this format (ie not a traditional book). We will see how it goes for the users.

**Comment by meganrwong** [comment]
Chapter 5 for review - 
https://github.com/ANZSoilData/def-au-scma/tree/main/html/5-soluble-Cl

5A2a Fig 5.3, 5.3 are referred to in this chapter, but talked about (and figures are placed in) method 5A2b - with no hyperlink ref within 5A2b . Where should figures sit? 5A2b as in the book? 

5A3b - table 5.2 is in, and also referred to within 5A3a - do figures just sit in first mentioned method, and then cross referenced?

**Comment by dr-shorthair** [comment]
I would put the image in every 'page' where it is mentioned. 
The actual image is only stored once. 
But you want it immediately visible everywhere that it is mentioned. 
Also because if the 'original' citing page is later deprecated, the image may still be relevant in a non-deprecated page.

**Comment by meganrwong** [comment]
Megan - to check 6B2a when GitHack '429: Too Many Requests' resolves - had a few cross referenced pictures and tables added

**Comment by meganrwong** [comment]
chapter 7 - the 'notes for C1 methods' - I put at the end of each C1 method

**Comment by meganrwong** [comment]
all fragments have been broken out @dr-shorthair 
https://github.com/ANZSoilData/def-au-scma/tree/main/html
Copyright statement, front and back matter included here
What has not been included is front covers and index
Consideration required re where some linking may be required to procedure definitions eg 'warning' front matter page and appendices.

**Comment by dr-shorthair** [comment]
Well done. I've tweaked the filenames to help get a predictable sort-order.

**Comment by meganrwong** [comment]
done - description of methods, and all front and back matter of the manual, appendices etc, linked to each methods eg https://vocabs.ardc.edu.au/repository/api/lda/ub/soil-chemical-methods-australasia/scm3/resource?uri=http://anzsoil.org/def/au/scm/04A2
