### ISSUE TITLE
Make skos:definition into links to HTML defs

### ISSUE THREAD

**Issue by dr-shorthair** [ANZSoilData/def-au-scma#21]
In https://github.com/ANZSoilData/def-au-scma/blob/main/rdf/skosplay-scma-001.xlsx
for each line like `<http://anzsoil.org/def/au/scma/9A3a>` 
the `skos:definition` column should be `<https://raw.githack.com/ANZSoilData/def-au-scma/master/html/09-P/09A3a.html>`

**Comment by meganrwong** [comment]
Done. But we are missing the defs for the old version methods. I don't think there is an eVersion of the book. Trying to chase up.
