### ISSUE TITLE
SCMA-2011, SWCM-1992 delete concept that don't belong and link

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#24]
delete terms from SCMA-2011 not found in  SWCM-1992

**Comment by dr-shorthair** [comment]
? 
Are you working on the spreadsheet? 

I think the task is 
(i) delete rows in the sheet labeled SWCM-1992 that don't belong there. 
(ii) delete rows in the sheet labeled SCMA-2011 that don't belong there (I did a couple already)
(iii) add 'links' in the `dcterms:replaces` (and maybe `dcterms:isReplacedBy`) column to reflect the versioning relationships

**Comment by dr-shorthair** [comment]
Use the one called skosplay-scma-2.xslx
It has both sheets.

**Comment by meganrwong** [comment]
yes, that is the sheet I was in. 
Yes, those are the tasks I understand need doing. Will finish and update 

The only questions I have are in issue #25

**Comment by meganrwong** [comment]
iI think the task is
(i) delete rows in the sheet labeled SWCM-1992 that don't belong there.
(ii) delete rows in the sheet labeled SCMA-2011 that don't belong there (I did a couple already)
(iii) add 'links' in the dcterms:replaces (and maybe dcterms:isReplacedBy) column to reflect the versioning relationships


> ? Are you working on the spreadsheet?
> 
> I think the task is (i) delete rows in the sheet labeled SWCM-1992 that don't belong there. (ii) delete rows in the sheet labeled SCMA-2011 that don't belong there (I did a couple already) (iii) add 'links' in the `dcterms:replaces` (and maybe `dcterms:isReplacedBy`) column to reflect the versioning relationships

pushed these - 
(i) done. Also updated all dcterms:source to URN:ISBN:978-0-909605-68-1
(ii) done
(iii) in SCMA-2011 we now have:
example - 05A2a dcterms:replaces s:05A2 and  s:05A2b dcterms:replaces s:05A2
in SWCM-1992 we have
example - s:05A2 dcterms:isReplacedBy s:05A2a , s:05A2b
questions - re (iii) 
1. in SCMA-2011 we also have s:05A2 in skos:broader . I guess it does not hurt if s:05A2  is in skos:broader and determs:replaces ? if so,  in SWCM-1992 should 05A2 have skos:narrower s:05A2a  and s:05A2b ?
2. "add to reflect versioning". Sorry - it is still a bit of mystery how to do this in 'isReplacedBy' and 'Replaces' when the IRIs are the same between the two versions. Or at least, that is how I interpret what has been done so far/your previous comments. I'm still a bit confused about this sorry. You will have to talk me through, relates to #25

**Comment by meganrwong** [comment]
some more follow up:
Outstanding - 
Question- chapter 1 in 1992 was not ReplacedBy anything in 2011. Chapter 1 in 2011 is 'introduction'. So, should chapter 1 concepts be 'deprecated' or similar? atm I have in skos:note 'Retired in Soil Chemical Methods Australasia, Rayment G.E. and Lyons D.J. ISBN  9780643101364, URN:ISBN:978-0-643-10218-7'

Follow up -  Need to confirm that 05A3a and 05A3b were split out this way in the 1992 version (that there was not a 05A3 in 1992).

**Comment by dr-shorthair** [comment]
1. On balance I prefer the NLA identifiers for the books https://catalogue.nla.gov.au/Record/685915 and https://catalogue.nla.gov.au/Record/4854518
2. I've fixed the column heading to indicate that "," is a separator
3. for 'deprecated' set `isReplacedBy` to `owl:Nothing`. The note is good - that explains it. 
4. I think the logic of the 05A2 broader/replaced is fine. There will be other cases where 'replaced' is not a case of 'narrower' etc. 
5. If the IRI is the same then it is the same thing - there is no replacement. If the definition has changed in a substantial way, then it is no longer the same thing and should get a different URI. If the text has been refined but it is still the same intention, then the URI can stay the same. If there is a superseded _annotation_ that you want to preserve, then put it in a `historyNote`. I've added a column for that. 

There are still nearly the same number of rows in both sheets. Is this correct??

**Comment by dr-shorthair** [comment]
I think we should delete all the hyperlink values from the  `skos:definition` column in SWCM-1992. We know that thos defs are all from 2011, right? No point in having them in the 1992 sheet.

**Comment by meganrwong** [comment]
> 1. On balance I prefer the NLA identifiers for the books https://catalogue.nla.gov.au/Record/685915 and https://catalogue.nla.gov.au/Record/4854518
> 2. I've fixed the column heading to indicate that "," is a separator
> 3. for 'deprecated' set `isReplacedBy` to `owl:Nothing`. The note is good - that explains it.
> 4. I think the logic of the 05A2 broader/replaced is fine. There will be other cases where 'replaced' is not a case of 'narrower' etc.
> 5. If the IRI is the same then it is the same thing - there is no replacement. If the definition has changed in a substantial way, then it is no longer the same thing and should get a different URI. If the text has been refined but it is still the same intention, then the URI can stay the same. If there is a superseded _annotation_ that you want to preserve, then put it in a `historyNote`. I've added a column for that.
> 
> There are still nearly the same number of rows in both sheets. Is this correct??

This all looks good

> There are still nearly the same number of rows in both sheets. Is this correct??
ANSWER - yes, about the same number of concepts between books - only handful of split outs of methods between version 1 and 2, and version 2 did not include chapter 1 codes

> 5. If the IRI is the same then it is the same thing - there is no replacement. If the definition has changed in a substantial way, then it is no longer the same thing and should get a different URI. If the text has been refined but it is still the same intention, then the URI can stay the same. If there is a superseded _annotation_ that you want to preserve, then put it in a `historyNote`. I've added a column for that.

FOLLOW UP for MW - Thank you this is a good explanation. So the question is does the description reflect same intention, or does it create a new thing/method. For example a change in chemical or procedure that gives a different result may be a change in method/thing and so 2A1 version 1 and 2A1 version 2 should have different IRIs (potentially). I think this is a question for those that reviewed the book. To my understanding Bruce Shelly I'm meeting w Fri is one of those people - I can ask him. 

Outstanding - 
Follow up for MW - 1992 is available as print book only. Task to track down if someone has definition text for 1992 - will ask Bruce S

**Comment by meganrwong** [comment]
resolves #25

**Comment by meganrwong** [comment]
Confirmed with Bruce Shelly - For each concept (eg 2A) the descriptions between the two version reflect same intention. Hence, they keep the same code between versions. They are the same thing between the two versions, so should have the same URI. As we have in current version/sckos-play-scma-2 - no changes required to URIs.

**Comment by meganrwong** [comment]
1992 and 2011 - two concept schemes created. 
where codes were retained between books, then the intent of method is same, so they were given the one identifier (they are the same method). That one method is then made a member of both 1992 and 2011 concept schemes
