### ISSUE TITLE
delete SCMA-2011 skos:definitions from SWCM-1992

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#25]
@dr-shorthair my understanding is that we don't want the skos:definitions (ie the raw.githack links)  from 2011 in the 1992 version. since for example '2A1' in 1992 version may have different definition to '2A1' in 2011

**Comment by dr-shorthair** [comment]
If it has the same identity, then the definition should be the same ... (in intnetion, even if the words are different)
It is best *not* to have multiple `skos:definition` field with different values. 
If there is an interest in preserving some earlier text, then it could go in a `skos:historyNote` column, with the variant text prepended with "[1992 definition]" (my suggestion).

**Comment by meganrwong** [comment]
I am a bit confused. I thought that the concepts should have different identities, ie 
2A1 from 1992 should be  http://anzsoil.org/def/au/scma/swcm-1992/2A1 
is ReplacedBy
2A1 from 2011 should be http://anzsoil.org/def/au/scma/scma-2011/2A1
They are from different concept schemes and have different identities, 
They can have different skos:definitions ie 
- SKOSPlay sheet SCMA-2011 has definitions in skos:definition column 
- SKOSPlay sheet SCMA-1992 has NO definitions in skos:definition column - becuase we don't have the definitions from the 1992 version available. There may be subtle differences between the definition content (though, perhaps not, will check w Bruce Shelly on Friday before deleting - he worked on the green book revisions I believe)

So, I don't understand why at https://demo.vocabs.ardc.edu.au/viewById/635 we have ' This concept is present in multiple locations within this vocabulary' 
when I think they should be different concepts? 

Or, are you saying (and what I"m seeing in RVA is) that 2A1 should be in two different concept schemes, but have the same identities?

**Comment by meganrwong** [comment]
I suspect that data custodian might need separate identifiers for their historical data v post 2011 data . They could be viewed as different methods enough to justify a different identifier? Not sure. May be q question for Bruce Shelly Friday

**Comment by meganrwong** [comment]
why does 07A3 also appear as an 'unordered collection'? 
![image](https://user-images.githubusercontent.com/49380601/157166164-4c871fc8-2212-4ba0-a81b-f850bab5d8c5.png)

**Comment by dr-shorthair** [comment]
If you look carefully you will see that all the concepts are in a single namespace 
- http://anzsoil.org/def/au/scma/
- 
But there are two different concept schemes 
- http://anzsoil.org/def/au/scma/swcm-1992 
- http://anzsoil.org/def/au/scma/scma-2011
- 
i.e. the concept scheme membership is _not_ implied by the URI path, rather it is an explicit property.

**Comment by meganrwong** [comment]
here is the current version with separate ConceptSchemes for the 1997 and 2011 handbooks - [https://demo.vocabs.ardc.edu.au/viewById/635](https://protect-au.mimecast.com/s/O-maCoV1R5I8qYo6UzBiD1?domain=demo.vocabs.ardc.edu.au)

working on
