### ISSUE TITLE
notes, references, back and front matter integration

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#26]
There are notes and references at the end of each chapter that relate to the methods within each chapter. 

Thoughts on how best to link in?

Is the place to put them in the skos:definitions of each skos:Collection 
eg http://anzsoil.org/def/au/scma/03 ?

If so, should we put the html of the notes and references within the fragment or put the hyperlink in?  https://raw.githack.com/ANZSoilData/def-au-scma/master/html/03/03.html

**Comment by meganrwong** [comment]
Should the front and back matter go into 
dcterms:description
of the concept scheme? 
As hyperlinks?
Front matter includes 'copyright', info page about authors, 'intro' (which has some notes on safety, compliance etc when undertaking methods) and general safety 'warning' re all methods. 
Backmatter from memory includes things like table for reporting/UoM, confidence levels for methods, and glossary

**Comment by dr-shorthair** [comment]
There may be some more precise places to put it:
- copyright &rarr; `dcterms:rights` and `dcterms:rightsHolder`
- authors &rarr;  `dcterms:creator`
- intro, warning &rarr;  `skos:note` or `rdfs:comment` 

I think I would put the backmatter in a set of `skos:related` links.

**Comment by meganrwong** [comment]
I like your thinking, will give it a go

**Comment by dr-shorthair** [comment]
Don't forget to pull a fresh copy from GitHub every time, *before* you start making changes. 
Else we may have clashing versions.

**Comment by meganrwong** [comment]
@dr-shorthair 
1. Wondering if front and back matter should go in notes and related material of the concepts that are only in the 1991, given the matter is from 2011. If we wanted to add them, in SKOPlay! the links would only still need to be added to the 1992 only concepts right? 
2. I don't know how much we should chase the specific front and back matter for the 1991 version..... I suspect we've got enough info in now for v1 milestone 
3. Also, I've only asked Bruce S for the descriptions for concepts replaced or deprecated from 1992. Hoping this is ok, we could have all the descriptions from 1992 in related material or somewhere, but don't think it is crucial for first version milestone

**Comment by meganrwong** [comment]
I'm done in here now Simon, aside from the questions for you here, and waiting for the descriptions from Bruce S. 
Would be good to revise together and push to RVA, and discuss any steps remaining to meet  'version 1' for ANSIS milestone

**Comment by bsimons14** [comment]
@meganrwong 
"Also, I've only asked Bruce S for the descriptions for concepts replaced or deprecated from 1992. Hoping this is ok, we could have all the descriptions from 1992 in related material or somewhere, but don't think it is crucial for first version milestone"
What descriptions, from where?

**Comment by meganrwong** [comment]
> @meganrwong "Also, I've only asked Bruce S for the descriptions for concepts replaced or deprecated from 1992. Hoping this is ok, we could have all the descriptions from 1992 in related material or somewhere, but don't think it is crucial for first version milestone" What descriptions, from where?

Oh Hi Bruce..... Sorry! Two Bruce Ss..... this is Bruce Shelly. Sorry to bother you :)

**Comment by dr-shorthair** [comment]
> What descriptions, from where?

The text from the 1992 edition. From Bruce Shelly of course.
