### ISSUE TITLE
version 1 check in demo

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#27]
https://demo.vocabs.ardc.edu.au/viewById/904

in 1992 - very small things

https://catalogue.nla.gov.au/Record/685915 was dct:license, changed to dcterms:isFormatOf in excel  and .ttl (just direct in text editor so we've not lost our edits required for RVA upload)

skos:editorialNote "The data was converted from a HTML representation to this 'linked-data' format
question - from HTML or hard copy?

edited description and notes - 
![image](https://user-images.githubusercontent.com/49380601/159847457-c9de382f-53be-4053-86b2-b162823da474.png)
 
The only remaining question I have is around title of whole thing 
Currently - Soil chemical methods - Australasia (SCMA)
possibilities - 
Soil Chemical Methods (Rayment and Higginson 1992; Rayment and Lyons 2011)
Soil Chemical Methods (SWCM 1992; SCMA 2011) (is there acronym book 1992 is well known by?
Soil Chemical Methods Australasia (1992, 2011)
and depending on intention to expand?
Soil Chemical Methods Australia 
Soil Chemical Methods Australasia

It all looks good though.
The concepts that were replaced by/replace are all working well

**Comment by dr-shorthair** [comment]
I'd go with one of 

- Soil Chemical Methods Australia
- Soil Chemical Methods Australasia

since the intention is to revise in-place. 
We only added the (SCMA) acronym when we were fighting against the existence of a previous version. 

Looks like you got the text sorted out nicely.
