### ISSUE TITLE
Reload SCM with updated URIs

### ISSUE THREAD

**Issue by dr-shorthair** [ANZSoilData/def-au-scma#29]
In https://github.com/ANZSoilData/def-au-scm/blob/main/rdf/scm.ttl the namespace has been updated to http://anzsoil.org/def/au/scm/ - **/scm/** rather than **/scma/** so that the definitions are not tied only to one source (SCMA is the acronym of the 2011 Green Book). 

This version of the vocabulary needs to be loaded into RVA, replacing https://vocabs.ardc.edu.au/viewById/634 

Then the URI resolution needs to be updated

**Comment by ljgregory** [comment]
Can you please walk me through the upload to RVA process or if Megan already knows how to do this, then please let me know when it is ready for us to set up the URI's. Noting this will mean a change to the already established persistent URIs

**Comment by dr-shorthair** [comment]
Megan has to do the first step. She is the owner of the vocab in RVA. 

> Noting this will mean a change to the already established persistent URIs

Indeed. But I don't think the previous ones have been used anywhere yet, so we have a chance to fix this before they are. They've only been up a couple of months. Or do you think otherwise?

**Comment by ljgregory** [comment]
I think the TERN soil data federator is making use of the scma codes, but can talk to Ross about updating or even keep both through the transition.

**Comment by dr-shorthair** [comment]
Its OK if they are using the codes. 
If they are using the URIs then we'd need to ask them to update. 

You are totally correct to catch the issue. If we can change then best to do it early.

**Comment by meganrwong** [comment]
Reloaded at demo site. Can you see this? 
https://demo.vocabs.ardc.edu.au/viewById/904

The collection title/RVA metadata has been changed to reflect that it is a vocabulary (soil chem methods) that currently consists of x 2 concept schemes (SCMA, SWCM)

http://anzsoil.org/def/au/scm/scma-2011
http://anzsoil.org/def/au/scm/swcm-1992

This structure should allow this vocabulary 'scm' to be expanded with other soil chem method lists (concept schemes)

note, for the codes retained from 1992 in 2011 - the methods have the same intent. No changes have occured to the method that would, say, yield a different result.  So, they are the same method (concept/same URI). 

Example 
http://anzsoil.org/def/au/scm/02B1
represents both the scma and swcm method '2A1'. They are the same method (have the same intent), may only differ in slight improvements for e.g. to clarity of definitions. The definitions of both the 2011 and 1992 will be stored with this concept. We have the 2011 descriptions in. We still need the 1992 definitions in (they are in PDF)

**Comment by meganrwong** [comment]
question - do we want to get rid of the html and just use text in dcterms description field of the x2 concept schemes?

https://demo.vocabs.ardc.edu.au/repository/api/lda/ub/soil-chemical-methods-australasia-scma/scm/resource?uri=http://anzsoil.org/def/au/scm/scma-2011

**Comment by meganrwong** [comment]
is this ok to publish? 

does anyone want to/need to talk to Ross

VAS are using - but we can just tell Bruce/Heath to update VAS to new URIs

**Comment by dr-shorthair** [comment]
@ljgregory can you check with Ross please?

**Comment by ljgregory** [comment]
Planning to, but he is in SA this week.

**Comment by dr-shorthair** [comment]
> Reloaded at demo site. Can you see this?
> https://demo.vocabs.ardc.edu.au/viewById/904

Can you adjust the setting to also show ConceptSchemes 
![image](https://user-images.githubusercontent.com/608303/182526353-1bbe8ee6-9071-402e-b7a5-94fe11593c26.png)

**Comment by meganrwong** [comment]
oops of course, apologies should have remembered we have those - done

**Comment by dr-shorthair** [comment]
I've removed the HTML markup in the concept-scheme descriptions

**Comment by meganrwong** [comment]
any progress w Ross confirming we are right to change roots of IRIs as we propose/have encoded in demo vesion @ljgregory ? I've a project inquiring re codes but rather not publicize till this issue is resolved

**Comment by meganrwong** [comment]
@ljgregory can we just tag Ross here? Would be good to resolve asap

**Comment by ljgregory** [comment]
Might be best to meet with him to discuss. Would Monday work?

________________________________

**Comment by meganrwong** [comment]
published  
https://vocabs.ardc.edu.au/viewById/634
@dr-shorthair you may want to take look at
I wondered it the URI was unique enough for when collection expands it scm/03 -  but recall it was done like this because these methods across both concept schemes scm and swcm (check should not be /scm/scma, scm/scma-swcm or something)

**Comment by dr-shorthair** [comment]
@ljgregory can you redo the anzsoil.org redirects here please? 

old- http://anzsoil.org/def/au/scma/*

new - http://anzsoil.org/def/au/scm/*

**Comment by dr-shorthair** [comment]
Lovely
