### ISSUE TITLE
definitions

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#3]
Required. Dicussion/plan for getting the defs from the online version to this controlled-vocabulary.

**Comment by dr-shorthair** [comment]
Need to decide how much you need for a definition. 
Would need to get agreement of the publisher if planning on >10% of the text, and probably even for that much. 
Who is talking with the publisher? (And who is managing the revision??)  

I note that the 'Procedure' section in each method is between 10% and 90% of the text. 
This is a non-trivial issue.

**Comment by meganrwong** [comment]
confirming - agreement with publisher? If so, this will be 
Fixed by #15 
and can close
