### ISSUE TITLE
html in dcterms

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#30]
do we want to get rid of the html and just use text in dcterms description field of the x2 concept schemes?

https://demo.vocabs.ardc.edu.au/repository/api/lda/ub/soil-chemical-methods-australasia-scma/scm/resource?uri=http://anzsoil.org/def/au/scm/scma-2011

**Comment by meganrwong** [comment]
Simon removed the HTML markup in the concept-scheme descriptions

**Comment by dr-shorthair** [comment]
https://github.com/ANZSoilData/def-au-scm/issues/29#issuecomment-1203506802 
https://github.com/ANZSoilData/def-au-scm/commit/6c87441860924ab8b492b0671497c3681a3e5db8
