### ISSUE TITLE
changes from concept (method) to collection

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#33]
The following have front/start steps of the methods that proceed them. 
They do not have 'report as' at the end of them. 
They perhaps should be changed type procedure concept to collections
They are not methods (with 'report as') in either volume of the 'green book' (SWCM or SCMA)
6B4
7A6
7B
7C1
7D
9A
9B
9C
9C2
9E
9I
9J
9K
10B
13D
18F
19B

**Comment by meganrwong** [comment]
would require re-work to Nested Collections I think

**Comment by meganrwong** [comment]
I did mean to ask you about this @dr-shorthair   - do need to try nested collections? Once addressed if required I think we lodge to DAP #28

**Comment by dr-shorthair** [comment]
1. If they are not 'methods' they are not 'concepts' under the modeling approach we are using
2. if they are groups of methods then they are collections
3. groupings of groups are also collections - in SKOS you can next collections OK.

**Comment by meganrwong** [comment]
Yep, right. Thanks. Confirms we have nested collections here.

It was not until I considered that some codes do not have 'report as' (with unit) in their description, that I realized these codes are not actually methods (concepts). Although they do contain background text on the collection of methods, they are not themselves methods. 

I'll need to rework as nested collections
