### ISSUE TITLE
QUDT request cmol/L

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#42]
to be submitted

**Comment by meganrwong** [comment]
[like http://qudt.org/vocab/unit/CentiMOL-PER-KiloGM]
(http://qudt.org/vocab/unit/MOL-PER-L)

**Comment by meganrwong** [comment]
Need your review here  @abhritchie  as there are some things I don't understand 
I looked at http://qudt.org/vocab/unit/MOL-PER-L and  http://qudt.org/vocab/unit/CentiMOL-PER-KiloGM for this
- I'm not 100 % clear on what the conversionMultiplier is, conversion to what? SI units ie MOL here? is it that is it equal to 0.01 mol/L. Assuming this, I had conversion factor of 0.01
-  I get what 'dimension vectors' is now but don't have a full grasp of. so I just based it on another substance per volume's dimension vector identifier (MOL-PER-L)
- Also, not sure what the Quantity kinds could be :
- I think most applicable for our case is http://qudt.org/vocab/quantitykind/MolalityOfSolute
- Could also be (as well as) https://qudt.org/vocab/quantitykind/IonicStrength
- not specifically exclusive to water, but could also be - http://qudt.org/vocab/quantitykind/Solubility_Water
- (I'll stick it under all three Quantity kinds for now)


@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://qudt.org/vocab/unit/CentiMOL-PER-L>
  rdf:type <http://qudt.org/schema/qudt/Unit> ;
  <http://qudt.org/schema/qudt/conversionMultiplier> 0.01 ;
  <http://qudt.org/schema/qudt/hasDimensionVector> <https://qudt.org/vocab/dimensionvector/A1E0L-3I0M0H0T0D0> ;
  <http://qudt.org/schema/qudt/hasQuantityKind> <http://qudt.org/vocab/quantitykind/AmountOfSubstancePerUnitVolume> ;
  <http://qudt.org/schema/qudt/hasQuantityKind> <http://qudt.org/vocab/quantitykind/IonicStrength> ;
  <http://qudt.org/schema/qudt/hasQuantityKind> <http://qudt.org/vocab/quantitykind/MolalityOfSolute> ;
  <http://qudt.org/schema/qudt/hasQuantityKind> <http://qudt.org/vocab/quantitykind/Solubility_Water> ;
  <http://qudt.org/schema/qudt/isUnitOfSystem> <http://qudt.org/vocab/sou/SI> ;
  <http://qudt.org/schema/qudt/plainTextDescription> "1/100 of SI unit of amount of substance per litre" ;
  <http://qudt.org/schema/qudt/symbol> "cmol/L" ;
  <http://qudt.org/schema/qudt/ucumCode> "cmol.L-1"^^<http://qudt.org/schema/qudt/UCUMcs> ;
  <http://qudt.org/schema/qudt/ucumCode> "cmol/L"^^<http://qudt.org/schema/qudt/UCUMcs> ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
  rdfs:label "Centimole per litre"@en ;
.

**Comment by bsimons14** [comment]
Conversion to SI

**Comment by meganrwong** [comment]
Got ya, just worked that out, thanks Bruce!

**Comment by meganrwong** [comment]
just edited my question - I have questions about 'dimension vector' and 'quantity kinds'

**Comment by meganrwong** [comment]
ok, I've done the best I can now in the above now, let me know if you can see anything amiss..... appreciate your time @abhritchie & @bsimons14 . I'll get the hang of it.....

**Comment by bsimons14** [comment]
QUDT allows multiple QuantityKinds for any Unit as it is the observable property and some units can be applied to multiple properties. VAS limits each Unit to a single QuantityKind but this is purely an implementation strategy that may not be required for ANSIS.

**Comment by meganrwong** [comment]
https://github.com/qudt/qudt-public-repo/issues/672

**Comment by steveraysteveray** [comment]
Hi, I followed one of the links in the QUDT repo and ended up here. Couldn't help chiming in that the CentiMOL-PER-L can not have these two lines:
http://qudt.org/schema/qudt/hasQuantityKind http://qudt.org/vocab/quantitykind/IonicStrength ;
http://qudt.org/schema/qudt/hasQuantityKind http://qudt.org/vocab/quantitykind/MolalityOfSolute ;

...because those two quantity kinds have a different dimensionality.

I ran this quick query at [our SPARQL endpoint](https://www.qudt.org/fuseki/#/dataset/qudt/query)
```
SELECT *
WHERE {
  ?qk qudt:hasDimensionVector qkdv:A1E0L-3I0M0H0T0D0 .
?qk a qudt:QuantityKind .
}
```

which gives all the dimensionally commensurate quantity kinds that you could pick, as desired.

**Comment by meganrwong** [comment]
> Hi, I followed one of the links in the QUDT repo and ended up here. Couldn't help chiming in that the CentiMOL-PER-L can not have these two lines: http://qudt.org/schema/qudt/hasQuantityKind http://qudt.org/vocab/quantitykind/IonicStrength ; http://qudt.org/schema/qudt/hasQuantityKind http://qudt.org/vocab/quantitykind/MolalityOfSolute ;
> 
> ...because those two quantity kinds have a different dimensionality.
> 
> I ran this quick query at [our SPARQL endpoint](https://www.qudt.org/fuseki/#/dataset/qudt/query)
> 
> ```
> SELECT *
> WHERE {
>   ?qk qudt:hasDimensionVector qkdv:A1E0L-3I0M0H0T0D0 .
> ?qk a qudt:QuantityKind .
> }
> ```
> 
> which gives all the dimensionally commensurate quantity kinds that you could pick, as desired.

Thanks very much for your time with this QUDT submission first timer ;) I appreciate it

**Comment by meganrwong** [comment]
ok, thanks for the patience folks -  I'm learning! Do you recon I've got the right quantity kind here (and I've for the dimensionvector in now, and both the quantityKind have the same dimensionvector) - @dr-shorthair  ?

I just went as per MOL-PER-L : 

unit:CentiMOL-PER-L
  a qudt:Unit ;
  qudt:conversionMultiplier 0.01 ;
  qudt:hasDimensionVector dimensionvector:A1E0L-3I0M0H0T0D0 ;
  dcterms:description "1/100 of SI unit of amount of substance per litre" ;
  qudt:hasQuantityKind quantitykind:AmountOfSubstancePerUnitVolume ;
  qudt:hasQuantityKind quantitykind:Solubility_Water ;
  qudt:symbol "cmol/L" ;
  qudt:ucumCode "cmol.L-1" ;
  qudt:ucumCode "cmol/L" ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
  rdfs:label "Centimole per litre"@en ; 
.

**Comment by dr-shorthair** [comment]
I like 
`qudt:hasQuantityKind quantitykind:AmountOfSubstancePerUnitVolume ;`

But not sure about 
`qudt:hasQuantityKind quantitykind:Solubility_Water ;`

**Comment by meganrwong** [comment]
Again, thanks @steveraysteveray and apologies for my tardiness 
done  https://qudt.org/vocab/unit/CentiMOL-PER-L
