### ISSUE TITLE
QUDT request mol/tonne

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#43]
required

like http://qudt.org/vocab/unit/MOL-PER-KiloGM

**Comment by meganrwong** [comment]
Another one ready so submit I'd appreciate feedback on  @bsimons14 ?

1,000-fold of the SI base unit kilogram so conversion multiplier is 1,000

questions - based off example http://qudt.org/vocab/unit/MOL-PER-KiloGM

- why does his have   rdf:type <http://qudt.org/schema/qudt/DerivedUnit> ; when #42 does not? 
- It has QuantityKind 'MolarityofSolute' - Guessing this is here because solute can be on a weight (tonne) basis

@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://qudt.org/vocab/unit/MOL-PER-TONNE>
  rdf:type <http://qudt.org/schema/qudt/DerivedUnit> ;
  rdf:type <http://qudt.org/schema/qudt/Unit> ;
  <http://purl.org/dc/terms/description> "Mole Per Tonne (\\(mol/t\\)) is a unit of Molality"^^<http://qudt.org/schema/qudt/LatexString> ;
  <http://qudt.org/schema/qudt/conversionMultiplier> 1000 ;
  <http://qudt.org/schema/qudt/definedUnitOfSystem> <http://qudt.org/vocab/sou/SI> ;
  <http://qudt.org/schema/qudt/derivedCoherentUnitOfSystem> <http://qudt.org/vocab/sou/SI> ;
  <http://qudt.org/schema/qudt/expression> "\\(mol/t\\)"^^<http://qudt.org/schema/qudt/LatexString> ;
  <http://qudt.org/schema/qudt/hasDimensionVector> <http://qudt.org/vocab/dimensionvector/A1E0L0I0M-1H0T0D0> ;
  <http://qudt.org/schema/qudt/hasQuantityKind> <http://qudt.org/vocab/quantitykind/AmountOfSubstancePerUnitMass> ;
  <http://qudt.org/schema/qudt/hasQuantityKind> <http://qudt.org/vocab/quantitykind/IonicStrength> ;
  <http://qudt.org/schema/qudt/hasQuantityKind> <http://qudt.org/vocab/quantitykind/MolalityOfSolute> ;
  <http://qudt.org/schema/qudt/isUnitOfSystem> <http://qudt.org/vocab/sou/SI> ;
  <http://qudt.org/schema/qudt/symbol> "mol/t" ;
  <http://qudt.org/schema/qudt/ucumCode> "mol.t-1"^^<http://qudt.org/schema/qudt/UCUMcs> ;
  <http://qudt.org/schema/qudt/ucumCode> "mol/t"^^<http://qudt.org/schema/qudt/UCUMcs> ;
  <http://qudt.org/schema/qudt/uneceCommonCode> "C19" ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
  rdfs:label "Mol per Tonne"@en ;
.

**Comment by meganrwong** [comment]
and not sure why this one had  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> whilst #42 didn't , but seems no harm having

**Comment by bsimons14** [comment]
The QUDT mappings between objects are not necessarily complete or always consistent, which is not surprising given the extent of the work. I don't recall finding any actual errors when I mapped the QUDT v1 URIs CSIRO established to the v2 URIs QUDT established.

**Comment by meganrwong** [comment]
https://github.com/qudt/qudt-public-repo/issues/671

**Comment by meganrwong** [comment]
done
https://qudt.org/vocab/unit/MOL-PER-TONNE
Many thanks for publishing and sincere apologies for my tardiness @steveraysteveray
