### ISSUE TITLE
unsure of UoM for method 9J1 and 9J2

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#44]
Struggle to understand UoM for Phosphorus buffering capacity (PBC; units of mg/kg/log10 μg/L) and how /if we would need to request a UoM at QUDT 

https://raw.githack.com/ANZSoilData/def-au-scma/master/html/09-P/09J1.html

The method reports on two observable properties - The question concerns Phosphorus buffering capacity

**Comment by dr-shorthair** [comment]
Need to consult a chemist.

**Comment by meganrwong** [comment]
@ljgregory  - for Nel

**Comment by meganrwong** [comment]
Put this question to ASPAC - Graham and Nell. I wonder if it could be in IUPAC somewhere?

**Comment by meganrwong** [comment]
from Graham - I think these are either set a blank or just the wording INDEX. We do have quite a number of these indexes and ratios which are effectively unitless.

**Comment by meganrwong** [comment]
changed to http://qudt.org/vocab/unit/UNITLESS
