### ISSUE TITLE
UoM 

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#6]
In https://github.com/ANZSoilData/def-au-scma/blob/main/rdf/scma.ttl the concepts in chapter 9, eg http://anzsoil.org/def/au/scma/9A

A question raised was should UoM be part of this vocabulary w their own PIDs
I reviewed the UoM across the chapters. 
The recommended units of measure are not straight e.g. mg/kg, kg/ha-1 . They also include what it is a quantity of e.g. mg Cl/kg , mg N/kg
They say what could be the obsv property, and something about the conditions it was observed under
 eg 'report as water soluble Cl, mg Cl/kg, on an air-dried basis'
'Report as Organic Matter by LOI (%OM) on an oven dry basis. 
So, what would you pull out from the book for the UoM? 
To stay true to book, you would have to create for example mg Cl/kg 

Or, you could use/link eg QUDT mg/kg. But, I feel this is outside of the book and how they suggest to report results

**Comment by meganrwong** [comment]
Furthermore, plenty of soil data providers report with different UoM - there are more than one UoM that could be linked.

**Comment by meganrwong** [comment]
Also, providers use methods to measure observable properties for chemical substances/elements outside of what the green book says it should be used for. 
I imagine we will want to/will be storing units or measure, observable properties and possibly the chemical substance/elements being measured separate to the procedures

**Comment by meganrwong** [comment]
So, I'd imagine you want to/will be storing units or measure, observable properties and possibly the chemical substance/elements being measured separate to the coded procedures

**Comment by meganrwong** [comment]
Summary of our options - 

UoM will just be in the skos:definition of the procedure, as example 'report as water soluble Cl, mg Cl/kg, on an air-dried basis'. That is how we have at present.

link procedure to outside vocabulary 'mg/kg' (QUDT). 

New vocab/identifier for 'mg Cl/kg' 

Keeping in mind first task is representation of green book as is. Thoughts @ljgregory ?

**Comment by ljgregory** [comment]
Are you planning to add the procedure descriptions to the procedure concepts? If so, then this includes mention of uom, where it has been noted. Is that enough for people to look up? Perhaps we can we add a skos:note that highlights the uom?

Also, a bit of an alternative approach… have we considered using the qudt:QuantityKind? Built for observed water quality concepts (see https://www.mssanz.org.au/modsim2013/L6/simons.pdf) Bruce can probably give some guidance on how this worked out?

**Comment by meganrwong** [comment]
Yes, the procedure descriptions are being included that the UoM is noted in, as example  'report as water soluble Cl, mg Cl/kg, on an air-dried basis'
So, I think that would be enough for users in first instance. 

Thanks for ref @ljgregory . Yes, linking QUDT to the procedures, and the properties of objects of interest is a possibility. Here is a related issue - https://github.com/ANZSoilData/def-au-scma/issues/8

But, suspect this is outside of 1st deliverable of getting green book as is up with the descriptions......

**Comment by ljgregory** [comment]
I would tend to agree, for the green book, which has many inconsistencies, it is probably best just to rely on the description. Perhaps we are trying to build an ontology that is not supported by the current text.  These discussions will inform the development of a more formal governance process that could lead to a more comprehensive vocabulary suite to align with our data.

**Comment by dr-shorthair** [comment]
I have split up ch9 into separate files, one for each procedure - see https://github.com/ANZSoilData/def-au-scma/tree/main/html/9-P 
No editing, just a copy of the relevant lines from the HTML for the chapter. 

These HTML fragments could be used as-is for the `skos:definition`, else hosted separately and accessed as a link from `skos:definition`. Note that the SKOS schema allows the value of `skos:definition` to be either a literal or a resource, and the latter can be implemented as a URIreference - https://www.w3.org/TR/skos-reference/#notes 

I am not (yet) suggesting a definite implementation pattern, just exploring the burden of some options. 
These examples could be evaluated to see if there is a (semi-)consistent layout and headings.

**Comment by meganrwong** [comment]
Nell and Graham (ASPAC) Are reviewing the UoM. We have mapped (in .Excell) each procedure against the UoM that is stated in SCMA. We have provided these UoM from http://qudt.org/2.1/vocab/unit . They are also adding the chemical element that the procedure is a measure of.  Once this has been done by Nell and Graham we will progress thinking about how chemical element and UoM are integrated.

**Comment by meganrwong** [comment]
the elements - search https://www.ebi.ac.uk/ols/search?q=iron&groupField=iri&start=0&ontology=chebi or if not there, may be be in IUPAC. I can see you can dois, but I can't see how to get them for individual elements / compounds (they are within the definitions of their roles /activities (eg NO3 is under the definition of 'oxidant')

**Comment by meganrwong** [comment]
duplicates the chemical element issue of #40 
So I"m removing chemical element from this issue to that it just concerns UoM

**Comment by meganrwong** [comment]
Done - will require review by chemists though. Used UoM from QUDT for UoM stated in procedure description. 
https://github.com/ANZSoilData/def-au-scm/pull/53
